drop table belongsTo;
drop table isTypeOf;
drop table isPartOf;
drop table inContinent;
drop table Geoname;
drop table AdminDivision;
drop table Feature;
drop table PoliticalEntity;
drop table Continent;
